nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/rancher/elemental-ui/gh-pages/extensions/elemental/3.0.2-rc.2
  compressedEndpoint: >-
    https://raw.githubusercontent.com/rancher/elemental-ui/gh-pages/extensions/elemental/3.0.2-rc.2.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/kube-version: ">= 1.16.0-0"
    catalog.cattle.io/rancher-version: ">= 2.10.0-0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
    catalog.cattle.io/ui-version: ">= 2.7.2"
