nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/kube-version: ">= 1.16.0"
    catalog.cattle.io/rancher-version: ">= 2.9.0 < 2.10.0"
    catalog.cattle.io/ui-version: ">= 2.7.2"
